# Preprod — am-doc-viewer-ui
# Preprod app host only — am.asrax.in reserved for prod
environment: preprod
replicaCount: 1
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: >-
      am-apps-preprod-global-cors@kubernetescrd
  hosts:
    - host: am-preprod.asrax.in
      paths:
        - path: /doc-ui
          pathType: Prefix
global:
  image:
    imagePullSecrets:
      - name: ghcr-creds
    tag: "30940447906"
nodeSelector:
  role: services
