ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: doc-intelligence.local
      paths:
        - path: /v1/extractor
          pathType: Prefix

config:
  app:
    GMAIL_REDIRECT_URI: "http://doc-intelligence.local/v1/extractor/gmail/callback"
