ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: api.amportfolio.com
      paths:
        - path: /v1/extractor
          pathType: Prefix

vault:
  secretPaths:
    mongodb: 
      path: "secret/data/prod/infra/mongodb"
    kafka: 
      path: "secret/data/prod/infra/kafka"
    jwt:
      path: "secret/data/prod/apps/auth/jwt"
    google:
      path: "secret/data/prod/apps/docs/google"
    identity-oidc:
      path: "secret/data/prod/services/am-identity"
    service-oauth:
      path: "secret/data/prod/services/am-doc-intelligence"

config:
  app:
    GMAIL_REDIRECT_URI: "https://api.amportfolio.com/v1/extractor/gmail/callback"
