# Prod — am-email-extractor
environment: prod
replicaCount: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: >-
      am-apps-prod-global-cors@kubernetescrd,
      am-apps-prod-strip-prefix-apps@kubernetescrd
  hosts:
    - host: am.asrax.in
      paths:
        - path: /email
          pathType: Prefix
        - path: /gmail
          pathType: Prefix

vault:
  enabled: true
  secretPaths:
    mongodb:
      path: "apps/data/prod/infra/mongodb"
    kafka:
      path: "apps/data/prod/infra/kafka"
    identity-oidc:
      path: "apps/data/prod/services/am-identity"
    service-oauth:
      path: "apps/data/prod/services/am-doc-intelligence"
    google:
      path: "apps/data/prod/apps/docs/google"
    jwt:
      path: "apps/data/prod/apps/auth/jwt"

env:
  ALLOWED_ORIGINS: "https://am.asrax.in,http://localhost:3000"

config:
  app:
    GMAIL_REDIRECT_URI: "https://am.asrax.in/email/api/v1/gmail/callback"
