vault:
  secretPaths:
    mongodb:
      mappings:
        MONGODB_URL: "url"
    kafka:
      mappings:
        KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
    jwt:
      mappings:
        JWT_SECRET: "secret"
        SESSION_SECRET: "secret"
    google:
      mappings:
        GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
        GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET"
