name: am_doc_parser_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  http: ^1.6.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.1.1
  web: ^0.5.1  
  # Modern UI Modules
  am_common:
    git:
      url: https://github.com/AM-Portfolio/am-modern-ui.git
      path: am_common
      ref: db7e88b3e7d0eb28879109b797c90d1da8af473b
  am_design_system:
    git:
      url: https://github.com/AM-Portfolio/am-modern-ui.git
      path: am_design_system
      ref: db7e88b3e7d0eb28879109b797c90d1da8af473b
  am_auth_ui:
    git:
      url: https://github.com/AM-Portfolio/am-modern-ui.git
      path: am_auth_ui
      ref: db7e88b3e7d0eb28879109b797c90d1da8af473b
  am_library:
    git:
      url: https://github.com/AM-Portfolio/am-modern-ui.git
      path: am_library
      ref: db7e88b3e7d0eb28879109b797c90d1da8af473b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
