replicaCount: 1
port: 8080
healthPath: /actuator/health
language: java
entrypoint: "exec java -jar app.jar"
probes:
  liveness:
    path: /actuator/health
  readiness:
    path: /actuator/health

global:
  image:
    registry: ghcr.io/am-portfolio
    pullPolicy: Always
  vault:
    enabled: true
    role: "am-backend-role"
    authPath: "auth/kubernetes"
    serviceAccountName: "am-backend-sa"

image:
  repository: am-document-processor
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: false

security:
  automountServiceAccountToken: true

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

vault:
  enabled: true
  role: "am-backend-role"
  secretPaths:
    mongodb:
      path: "apps/data/preprod/infra/mongodb"
    kafka:
      path: "apps/data/preprod/infra/kafka"
    auth:
      path: "apps/data/preprod/services/am-auth"

config:
  app:
    SPRING_KAFKA_CONSUMER_GROUP_ID: "am-doc-intelligence"
    APP_KAFKA_TOPIC_DOCUMENT_UPLOADED: "document.uploaded"
    APP_KAFKA_TOPIC_DOCUMENT_PROCESSED: "document.processed"
