ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: api.amportfolio.com
      paths:
        - path: /doc/processor
          pathType: Prefix

vault:
  secretPaths:
    mongodb: 
      path: "secret/data/prod/infra/mongodb"
    kafka: 
      path: "secret/data/prod/infra/kafka"
    auth:
      path: "secret/data/prod/services/am-auth"
    identity-oidc:
      path: "secret/data/prod/services/am-identity"
    service-oauth:
      path: "secret/data/prod/services/am-document-processor"

env:
  SPRING_PROFILES_ACTIVE: "prod,security"
