vault:
  secretPaths:
    mongodb:
      mappings:
        MONGODB_URL: "url"
        MONGODB_DATABASE: "database"
    kafka:
      mappings:
        KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
        KAFKA_JAAS_CONFIG: "__jaas__"
    auth:
      mappings:
        JWT_SECRET: "JWT_SECRET_KEY"
        INTERNAL_JWT_SECRET: "JWT_SECRET_KEY"
