# Prod — am-cloudinary-manager
environment: prod
replicaCount: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: >-
      am-apps-prod-global-cors@kubernetescrd
  hosts:
    - host: am.asrax.in
      paths:
        - path: /v1/cloudinary
          pathType: Prefix

vault:
  enabled: true
  secretPaths:
    cloudinary:
      path: "apps/data/prod/services/am-cloudinary-manager"
    identity-oidc:
      path: "apps/data/prod/services/am-identity"
    service-oauth:
      path: "apps/data/prod/services/am-cloudinary-manager"
