vault:
  secretPaths:
    cloudinary:
      mappings:
        CLOUDINARY_CLOUD_NAME: "CLOUDINARY_CLOUD_NAME"
        CLOUDINARY_API_KEY: "CLOUDINARY_API_KEY"
        CLOUDINARY_API_SECRET: "CLOUDINARY_API_SECRET"
    identity-oidc:
      mappings:
        OIDC_JWKS_URI: "OIDC_JWKS_URL"
        OIDC_ISSUER_URI: "OIDC_ISSUER"
    service-oauth:
      mappings:
        OAUTH2_CLIENT_ID: "AM_CLOUDINARY_CLIENT_ID"
        OAUTH2_CLIENT_SECRET: "AM_CLOUDINARY_CLIENT_SECRET"

    otel:
      mappings:
        TRACING_SAMPLING_PROBABILITY: "TRACING_SAMPLING_PROBABILITY"
