name: AM Doc Viewer UI Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "test/**", "fix/**", "hotfix/**"]
    paths:
      - 'apps/am-doc-viewer-ui/**'
      - '.github/workflows/am-doc-viewer-ui-publish.yml'
  pull_request:
    branches: ["main", "develop"]
    paths:
      - 'apps/am-doc-viewer-ui/**'
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/central-build-publish-no-deploy.yml
    with:
      language: 'flutter'
      working_directory: 'apps/am-doc-viewer-ui'
      image_name: 'am-doc-viewer-ui'
      build_context: '.'
      skip_secrets_scan: true
    secrets: inherit
