name: AM Document Processor Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish UI
    permissions:
      contents: write
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: 'java'
      working_directory: 'services/am-document-processor'
      image_name: 'am-document-processor'
      build_context: 'services/am-document-processor'
      skip_secrets_scan: true
    secrets: inherit
