name: AM Doc Viewer UI Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish UI
    permissions:
      contents: write
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: 'flutter'
      working_directory: 'apps/am-doc-viewer-ui'
      image_name: 'am-doc-viewer-ui'
      build_context: '.'
      skip_secrets_scan: true
    secrets: inherit
