name: AM Email Extractor Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "test/**", "fix/**", "hotfix/**"]
    paths:
      - 'services/am-email-extractor/**'
      - '.github/workflows/am-email-extractor-publish.yml'
  pull_request:
    branches: ["main", "develop"]
    paths:
      - 'services/am-email-extractor/**'
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/central-build-publish-no-deploy.yml
    with:
      language: 'python'
      working_directory: 'services/am-email-extractor'
      image_name: 'am-email-extractor'
      build_context: '.'
      skip_secrets_scan: true
    secrets: inherit
