name: Debug Flutter Build
on:
  push:
    branches: ["**"]

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Git Config
        run: |
          git config --global url."https://x-access-token:${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Pub Get
        working-directory: apps/am-doc-viewer-ui
        run: flutter pub get > pub_log.txt 2>&1 || true
      - name: Build Web
        working-directory: apps/am-doc-viewer-ui
        run: docker build --build-arg BASE_REGISTRY=ghcr.io/am-portfolio/ --build-arg GITHUB_PACKAGES_TOKEN=${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }} -f Dockerfile . > build_log.txt 2>&1 || true
      - name: Commit log
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add apps/am-doc-viewer-ui/*.txt
          git commit -m "chore: upload build log [skip ci]" || echo "No changes to commit"
          git push
